callbacks:
  checkpoint:
    enabled: True
    monitor: "val_mIoU"
    save_top_k: 1
    mode: "max"
    dirpath: "experiments/floodnet_unet/checkpoints"
    filename: "cpkt-unet"
  early_stop:
    enabled: False
  lr_monitor:
    enabled: False
  device_stats:
    enabled: False
