logger:
  mlflow:
    enable: true
    tracking_uri: "http://127.0.0.1:8080"
    experiment_name: "FloodNet_MLFlow"
    save_dir: "plots/mlflow_logs"
  tensorboard:
    enable: true
    save_dir: "plots/tensorboard"
    name: "floodnet_unet"
